location /img-proxy {
    resolver 1.1.1.1 1.0.0.1 valid=300s ipv6=off;

    if ($arg_url = "") {
        return 400;
    }

    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_set_header Host gbisuropatimalang.com;
    proxy_set_header Referer https://gbisuropatimalang.com/;
    proxy_set_header User-Agent $http_user_agent;
    proxy_hide_header Access-Control-Allow-Origin;
    add_header Access-Control-Allow-Origin * always;
    add_header Cache-Control "public, max-age=3600" always;

    proxy_pass $arg_url;
}
